---
title: "Lab 7 Part 2 - Kriging"
author: "Mia Guarnieri"
date: "2/17/2022"
output: html_document
---

```{r setup, include = TRUE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(here)
library(sf)
library(tmap)
library(gstat)
library(stars)
```

# Read in CA map and groundwater depth data

```{r}
#read in counties
ca_counties_sf <- read_sf(here("data", "ca_counties"), 
                               layer = "CA_Counties_TIGER2016") %>% 
  janitor::clean_names() %>% 
  select(name)

#check projection
st_crs(ca_counties_sf)

#read in groundwater depth data
ca_dgw_sf <- read_sf(here("data", "ca_dgw", "F2013_DBGS_Points_20150720_093252.gpkg")) %>% 
  janitor::clean_names()

st_crs(ca_dgw_sf)

ca_dgw_sf <- st_transform(ca_dgw_sf, st_crs(ca_counties_sf))

ggplot() +
  geom_sf(data = ca_counties_sf)+
  geom_sf(data = ca_dgw_sf, aes(color = dgbs))
```

# More tmap

```{r}
tmap_mode(mode = "view")

tm_shape(ca_dgw_sf) +
  tm_dots("dgbs", palette = "Blues")

#tmaptools::palette_explorere() -- can mess around with this later
#need the shinyjs package
```

# Clip to just San Joaquin County

```{r}
sj_county_sf <- ca_counties_sf %>% 
  filter(name == "San Joaquin")

#keep observations for groundwter depth in that county
sj_depth_sf <- ca_dgw_sf %>% 
  st_intersection(sj_county_sf)

ggplot() +
  geom_sf(data = sj_county_sf) +
  geom_sf(data = sj_depth_sf, aes(color = dgbs)) +
  theme_void() +
  scale_color_viridis_c()
```
## Check for duplicate locations

```{r}
well_duplicates <- sj_depth_sf %>% 
  janitor::get_dupes(latitude, longitude)

sj_depth_sf <- sj_depth_sf %>% 
  filter(!local_well %in% well_duplicates$local_well)
```

# Create a variogram

```{r}
sj_dgw_vgm <- variogram(dgbs ~ 1, data = sj_depth_sf) 
#will calculate an intercept it will use as a mean for ordinary kriging

plot(sj_dgw_vgm)
```

## Create the vriogram model

```{r}
sj_dgw_vgm_fit <- fit.variogram(sj_dgw_vgm,
                                model = vgm(model="Gau",
                                            nugget = 20,
                                            sill = 3000,
                                            range = 32000))

plot(sj_dgw_vgm, sj_dgw_vgm_fit)
```















